version: '3.1'

services:

  mongo-server-check:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-server-check:27017/
  docker-build-file:
    build: .